server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: Andya@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      
  application:
    name: ORDER-SERVICE
    
    
  eureka:
    instance:
      hostname: false
      preferIpAddress: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
